### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by henrique-andrade**
Add Brazilian Portuguese translation to Time Limit

### CODE REVIEW

**Comment by marbetschar** [comment]
@henrique-andrade thank you so much for the translation!! Any concerns about changing `pt_BR` to `pt`? Not too familiar with Portuguese but IMHO its better to have "a" Portuguese translation instead of none :)

**Comment by marbetschar** [comment]
@henrique-andrade I'm merging it as it is - we can still iterate later on. Thanks again for the PR!

**Comment by henrique-andrade** [comment]
> @henrique-andrade thank you so much for the translation!! Any concerns about changing `pt_BR` to `pt`? Not too familiar with Portuguese but IMHO its better to have "a" Portuguese translation instead of none :)

Dear Marco, Brazilian and European Portuguese are very close, but the small differences can make the translation weird 🤣

I going to try to talk to a Portuguese friend to advise me about the translation.

Last but not least: thank you so much for you app! It's helping me a lot to manage my time!

**Comment by marbetschar** [comment]
> Dear Marco, Brazilian and European Portuguese are very close, but the small differences can make the translation weird 🤣
> I going to try to talk to a Portuguese friend to advise me about the translation.

I see. I merged your translation as `pt` - so feel free to open a new issue in case we need both translations!

> Last but not least: thank you so much for you app! It's helping me a lot to manage my time!

Glad to hear!! 😍

**Comment by hugok79** [comment]
@henrique-andrade
Portuguese "European Portuguese" added: https://github.com/marbetschar/time-limit/pull/65

@marbetschar To get familiar with Portuguese you can take a look: https://www.youtube.com/watch?v=Nur6WwpmyBo

**Pull request merged**
