### PR TITLE
Flatpak

### LINKED ISSUE #45: Flatpak
Since we are gointg to Flatpak all the things for Odin, Time Limit should also be shipped as Flatpak.

### PR DESCRIPTION
**Pull request by marbetschar**
Fixes #45.

### CODE REVIEW

**Comment by hanaral** [comment]
last time I tried it was complaining about libunity missing - have you swapped out the unity stuff for granite.utilities?

**Comment by marbetschar** [comment]
Yes, [dropped libunity](https://github.com/marbetschar/time-limit/pull/49). Flatpak seems to build now, however when I try to start Time Limit it throws the error below - not sure why:

```
$ flatpak run com.github.marbetschar.time-limit 
Gtk-Message: 13:19:40.226: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:19:40.227: Failed to load module "canberra-gtk-module"

** (com.github.marbetschar.time-limit:2): WARNING **: 13:19:40.233: Clock.vala:104: Could not connect: No such file or directory

** (com.github.marbetschar.time-limit:2): CRITICAL **: 13:19:40.332: Settings.vala:87: Could not connect: No such file or directory

** (com.github.marbetschar.time-limit:2): CRITICAL **: 13:19:40.332: Settings.vala:109: Could not connect: No such file or directory
```

**Comment by hanaral** [comment]
Did you add the settings daemon and dbus permissions in the manifest?

**Comment by marbetschar** [comment]
Nope. I'm completely new to Flatpak packaging - so I simply copied the YAML file from the docs as a starting point. No additionas done yet. How do I do so?

**Comment by hanaral** [comment]
looks like I got it right lol:
Screenshot from 2021-05-04 12-29-42

**Comment by marbetschar** [comment]
Worked. But the Flatpack'ed version has still some issues: It does not recognize the enabled dark mode and (at least on my end) the header bar styling is wrong. Any clue why?

Screenshot from 2021-05-04 13 37 33

Left: Deb package version, Right: Flatpack'ed version

**Comment by hanaral** [comment]
Colour scheme - Maybe the app is relying on the hardcoded gtk style changing rather than catching the granite util for switching theme
as for the styling issue; did you hardcode the elementary theme anywhere? the original 'elementary' theme doesn't exist anymore

**Comment by marbetschar** [comment]
https://github.com/marbetschar/time-limit/blob/756ff4ff41959dfcb2dee8bb89976756b835f573/src/Application.vala#L79-L86

**Comment by hanaral** [comment]
That's odd, it's fully funcional on my end:
2021-05-04 12 47 34 のスクリーンショット
2021-05-04 12 47 43 のスクリーンショット

**Comment by hanaral** [comment]
Are you using the up-to-date SDK from the new repo? (https://flatpak.elementary.io/appcenter.flatpakrepo)

**Comment by marbetschar** [comment]
I installed the SDK yesterday as documented [here](https://docs.elementary.io/develop/writing-apps/the-basic-setup#flatpak) - so this should be fine.

Anyway; I installed my daily build quite some time ago and my windows do not have rounded corners and the accent color option is missing in my System Settings too. So I guess my installed is somehow broken.

Do notifications also work on your end? If so, I'm merging the code into master since its an improvement either way. And I will do a fresh install somewhen soon...

**Comment by hanaral** [comment]
Notifications work fine for me, nothing is broken afaict. You might want to rebuild the settings-daemon and the default-settings, I had a buggy install a while ago and it fixed a lot of the stuff for me

**Comment by marbetschar** [comment]
A reboot fixed the problem :man_shrugging:

**Comment by hanaral** [comment]
It must've been a settings-daemon or gala not-applying-its-updates-thing then 🤷‍♂️

**Pull request merged**
